### ISSUE TITLE
Using IPs instead of localhost for nodetool commands breaks dtests

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#171] opened 2019-08-29 13:34 UTC
ccm version 1545f3e412dec122c4d97044b162de9a53edbdbf
dtest version scylladb/scylla-dtest@1cd840d8c575fdc68723152f85ce0c1bcc085c3c

pull #170 assumes we listen on the cluster host address but it still listens on `localhost:(7000 + cluster.id * 100 + node.id)`

This change broke a few dtests.  E.g.:
[dtest-release/227/testReport/migration_test/TTLWithMigrate/big_table_with_ttls_test](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/227/testReport/migration_test/TTLWithMigrate/big_table_with_ttls_test/):
```
Error Message
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/repository/3.11.3/bin/nodetool -h 127.0.42.1 -p 7142 refresh -- ks cf' failed; exit status: 1; stderr: nodetool: Failed to connect to '127.0.42.1:7142' - ConnectException: 'Connection refused (Connection refused)'.
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/migration_test.py", line 937, in big_table_with_ttls_test
    count_query=count_query)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/migration_test.py", line 959, in migrate_to_cassandra
    keyspace_names_list=[keyspace_name], table_names=[table_name])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 1141, in run_migration
    self.migrate_data_to_cassandra(nodes=nodes_list)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 1115, in migrate_data_to_cassandra
    node.nodetool("refresh -- {} {}".format(ks.replace('"', ''), table.replace('"', '')))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 721, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/repository/3.11.3/bin/nodetool -h 127.0.42.1 -p 7142 refresh -- ks cf' failed; exit status: 1; stderr: nodetool: Failed to connect to '127.0.42.1:7142' - ConnectException: 'Connection refused (Connection refused)'.
```

1. We also need to pass to scylla-jmx com.sun.management.jmxremote.host
2. I'm not sure if it's used anywhere but jconsole still uses localhost

**Comment by bhalevy** [comment] 2019-08-29 13:54
Sorry I was wrong, the problem is not with this change.
It would still be a good idea to provide the node address to the scylla-jmx instance though.

**Comment by fruch** [comment] 2019-08-29 14:06
this might be related to the change
from the look of it this is 3.11.3, i.e. Cassandra that failing
we merged it based on the next-gating, which I guess doesn't touch Cassandra at all.

Lets revert CCM, and try those specific tests to figure this out.

**Comment by tarzanek** [comment] 2019-08-29 14:20
yeah, feel free to revert
however I'd like to know the command to reproduce the failing test:
`PRINT_DEBUG=true CASSANDRA_DIR=../scylla/build/release NOSE_PROCESSES=1 nosetests -s -v --process-timeout=1800 migration_test:TTLWithMigrate.big_table_with_ttls_test`
?

**Comment by bhalevy** [comment] 2019-08-29 14:21
Reproducing locally, I see this:
```
2019-08-29 16:48:07.533753 Starting Cassandra cluster version 3.11.3
2019-08-29 16:48:07.541107 Allocated cluster ID 36: /local/home/bhalevy/.dtest/dtest-ymq16D
2019-08-29 16:48:07.633312 Starting a Cassandra cluster of 4 node(s) with options {'hinted_handoff_enabled': False}...
...
2019-08-29 16:48:32.244825 Stopping Cassandra cluster
2019-08-29 16:48:44.319780 Test failed
...
NodetoolError: Nodetool command '/local/home/bhalevy/.ccm/repository/3.11.3/bin/nodetool -h 127.0.36.1 -p 7136 refresh -- ks cf' failed; exit status: 1; stderr: nodetool: Failed to connect to '127.0.36.1:7136' - ConnectException: 'Connection refused (Connection refused)'.
```

I wonder how Cassandra is listening on the jmx port

**Comment by tarzanek** [comment] 2019-08-29 14:39
Please revert then, I will look at above once I will know how to reproduce above test

**Comment by tarzanek** [comment] 2019-08-29 17:19
I can reproduce now with above, OK, so it seems Bennys analysis is true - cassandra listens only on localhost, not as scylla-jmx that listens on all IPs
So let me address this so I can proceed with nodetool over REST

**Comment by tarzanek** [comment] 2019-08-29 17:22
One of the ideas is to make cassandra behave similar like scylla-jmx, listen on all IPs for this test
https://github.com/scylladb/scylla-dtest/blob/0eb598a15909f7bb8dd9102719bc252269e673c8/scylla_tools.py#L1009

**Comment by fruch** [comment] 2019-08-29 17:35
I would look inside ccm code where to put "-Dcom.sun.management.jmxremote.host"

dtest code isn't the one starting jmx

**Comment by slivne** [comment] 2019-08-31 19:47
I am not supper happy with opening scylla-jmx to listen on local ip instead
of local host in scylla-ccm (it certainly should not be done by default)

- its not the setup we have in deployments for secutrity reasons - you
don't want someone to access jmx and decomission/remove a node

- when jmx is enabled to run on non localhost its using security settings.

**Comment by tarzanek** [comment] 2019-09-01 06:24
@slivne so in such case I will need to improve ccm that REST port will listen on "localhost" instead on respective local IPs
(since now scylla-jmx listens on localhost IPs, but REST port in scylla is exposed only on local IP, which is why this bug was filed in a first place)

**Comment by bhalevy** [comment] 2019-09-01 06:40
Confirmed with @amnonh.  We need to keep jmx on localhost.

**Comment by bhalevy** [comment] 2019-09-01 06:43
Let's revert 1545f3e412dec122c4d97044b162de9a53edbdbf then.

**Comment by slivne** [comment] 2019-09-01 07:04
@tarzanek - I am not sure this will be super easy for you ... we had to work around all he jmx using the same port.

Can you elaborate what is the issue you are trying to solve - I think scylla-jmx is able to cope with finding the api-address in some manner - maybe the correct thing is to copy the code from scylla-jmx @amnonh can you reference the part in the code in scylla-jmx that locates the rest api address.

**Closed** 2019-09-01 07:07 UTC
